// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void AnimationFenHao_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
lv_obj_t * ui_ScreenHome;
lv_obj_t * ui_PanelTime;
lv_obj_t * ui_LabelHour;
lv_obj_t * ui_LabelMin;
lv_obj_t * ui_Labelfenhao;
lv_obj_t * ui_LabelDate;
lv_obj_t * ui_LabelWeek;
lv_obj_t * ui_PanelHealth;
lv_obj_t * ui_ArcStepNum;
lv_obj_t * ui_ArcHeartRate;
lv_obj_t * ui_ArcBloodOxygen;
lv_obj_t * ui_LabelKeepOn;
lv_obj_t * ui_LabelStepNum;
lv_obj_t * ui_ImageStepNum;
lv_obj_t * ui_LabelBloodOxygen;
lv_obj_t * ui_ImageBloodOxygen;
lv_obj_t * ui_LabelHeartRate;
lv_obj_t * ui_ImageHeartRate;
lv_obj_t * ui_Imageble;
lv_obj_t * ui_ImageAlarm;
lv_obj_t * ui_ImageLongSit;
lv_obj_t * ui_PanelHum;
lv_obj_t * ui_ArcHum;
lv_obj_t * ui_ImageHum;
lv_obj_t * ui_LabelHum;
lv_obj_t * ui_PanelTem;
lv_obj_t * ui_ArcTem;
lv_obj_t * ui_ImageTem;
lv_obj_t * ui_LabelTem;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;


// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
void ui_event_ScreenMenu(lv_event_t * e);
lv_obj_t * ui_ScreenMenu;
lv_obj_t * ui_PanelMenu;
void ui_event_PanelCalendar(lv_event_t * e);
lv_obj_t * ui_PanelCalendar;
lv_obj_t * ui_LabelCalendar;
lv_obj_t * ui_ImageHRSPO3;
void ui_event_PanelHRSPO2H(lv_event_t * e);
lv_obj_t * ui_PanelHRSPO2H;
lv_obj_t * ui_LabelHRSPO2H;
lv_obj_t * ui_ImageHRSPO2;
void ui_event_PanelScreenBrightness(lv_event_t * e);
lv_obj_t * ui_PanelScreenBrightness;
lv_obj_t * ui_LabelScreenBrightness;
lv_obj_t * ui_ImageScreenBrightness;
//lv_obj_t * ui_PanelAlarm;
//lv_obj_t * ui_LabelAlarm;
//lv_obj_t * ui_ImageAlarmClk;
void ui_event_SwitchAlarm(lv_event_t * e);
//lv_obj_t * ui_SwitchAlarm;
//lv_obj_t * ui_PanelTurnOffLcd;
lv_obj_t * ui_LabelTurnOffLcd;
lv_obj_t * ui_ImageTurnOffLcd;
void ui_event_SwitchTurnOfLcd(lv_event_t * e);
lv_obj_t * ui_SwitchTurnOfLcd;
//lv_obj_t * ui_PanelTaiWangLiangPing;
void ui_event_SwitchTaiWanLiangPing(lv_event_t * e);
lv_obj_t * ui_SwitchTaiWanLiangPing;
lv_obj_t * ui_LabelTaiwanLiangPing;
lv_obj_t * ui_ImageTaiwanliangping;
//lv_obj_t * ui_PanelLongSit;
lv_obj_t * ui_LabelLongSit;
lv_obj_t * ui_ImageLongSitTX;
void ui_event_SwitchLongSit(lv_event_t * e);
lv_obj_t * ui_SwitchLongSit;


// SCREEN: ui_ScreenHRSPO2H
void ui_ScreenHRSPO2H_screen_init(void);
void ui_event_ScreenHRSPO2H(lv_event_t * e);
lv_obj_t * ui_ScreenHRSPO2H;
lv_obj_t * ui_PanelHR;
lv_obj_t * ui_SliderHR;
lv_obj_t * ui_LabelHR;
lv_obj_t * ui_ImageHR;
lv_obj_t * ui_PanelSPO2H;
lv_obj_t * ui_SliderSPO2H;
lv_obj_t * ui_LabelSPO2H;
lv_obj_t * ui_ImageSPO2H;


// SCREEN: ui_ScreenBrightness
void ui_ScreenBrightness_screen_init(void);
void ui_event_ScreenBrightness(lv_event_t * e);
lv_obj_t * ui_ScreenBrightness;
void ui_event_SliderBrightness(lv_event_t * e);
lv_obj_t * ui_SliderBrightness;
lv_obj_t * ui_ImageBrightness;
lv_obj_t * ui_LabelBrightness;


// SCREEN: ui_ScreenCalendar
void ui_ScreenCalendar_screen_init(void);
void ui_event_ScreenCalendar(lv_event_t * e);
lv_obj_t * ui_ScreenCalendar;
lv_obj_t * ui_Calendar;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void AnimationFenHao_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_opacity);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_ScreenHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenMenu_screen_init);
    }
	/*
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        AnimationFenHao_Animation(ui_Labelfenhao, 0);
    }
	*/
}
void ui_event_ScreenMenu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenHome_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadScreenMenu(e);
    }
}
void ui_event_PanelCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenCalendar, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenCalendar_screen_init);
    }
}
void ui_event_PanelHRSPO2H(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenHRSPO2H, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenHRSPO2H_screen_init);
    }
}
void ui_event_PanelScreenBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ScreenBrightness, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenBrightness_screen_init);
    }
}
/*void ui_event_SwitchAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        AlarmSwitch(e);
    }
}*/
void ui_event_SwitchTurnOfLcd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        SelfTurnOfflcdSwitch(e);
    }
}
void ui_event_SwitchTaiWanLiangPing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        RaiseWristTurnOnLcdSwitch(e);
    }
}
void ui_event_SwitchLongSit(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        LongSitSwitch(e);
    }
}
void ui_event_ScreenHRSPO2H(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadScreenHRSPO2H(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        UnLoadScreenSPO2H(e);
    }
}
void ui_event_ScreenBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadSceenBrightness(e);
    }
}
void ui_event_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        LcdBrightnessSlider(e);
    }
}
void ui_event_ScreenCalendar(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScreenMenu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_ScreenMenu_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadScreenCalendar(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ScreenHome_screen_init();
    ui_ScreenMenu_screen_init();
    ui_ScreenHRSPO2H_screen_init();
    ui_ScreenBrightness_screen_init();
    ui_ScreenCalendar_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ScreenHome);
}
