// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void AnimationFenHao_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
void ui_event_ScreenHome(lv_event_t * e);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_PanelTime;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelMin;
extern lv_obj_t * ui_Labelfenhao;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelWeek;
extern lv_obj_t * ui_PanelHealth;
extern lv_obj_t * ui_ArcStepNum;
extern lv_obj_t * ui_ArcHeartRate;
extern lv_obj_t * ui_ArcBloodOxygen;
extern lv_obj_t * ui_LabelKeepOn;
extern lv_obj_t * ui_LabelStepNum;
extern lv_obj_t * ui_ImageStepNum;
extern lv_obj_t * ui_LabelBloodOxygen;
extern lv_obj_t * ui_ImageBloodOxygen;
extern lv_obj_t * ui_LabelHeartRate;
extern lv_obj_t * ui_ImageHeartRate;
extern lv_obj_t * ui_Imageble;
extern lv_obj_t * ui_ImageAlarm;
extern lv_obj_t * ui_ImageLongSit;
extern lv_obj_t * ui_PanelHum;
extern lv_obj_t * ui_ArcHum;
extern lv_obj_t * ui_ImageHum;
extern lv_obj_t * ui_LabelHum;
extern lv_obj_t * ui_PanelTem;
extern lv_obj_t * ui_ArcTem;
extern lv_obj_t * ui_ImageTem;
extern lv_obj_t * ui_LabelTem;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
void ui_event_ScreenMenu(lv_event_t * e);
extern lv_obj_t * ui_ScreenMenu;
extern lv_obj_t * ui_PanelMenu;
void ui_event_PanelCalendar(lv_event_t * e);
extern lv_obj_t * ui_PanelCalendar;
extern lv_obj_t * ui_LabelCalendar;
extern lv_obj_t * ui_LabelHRSPO2H;
extern lv_obj_t * ui_ImageHRSPO3;
void ui_event_PanelHRSPO2H(lv_event_t * e);
extern lv_obj_t * ui_PanelHRSPO2H;
extern lv_obj_t * ui_LabelHRSui_ImageHRSPO2PO2H;
extern lv_obj_t * ui_ImageHRSPO2;
void ui_event_PanelScreenBrightness(lv_event_t * e);
extern lv_obj_t * ui_PanelScreenBrightness;
extern lv_obj_t * ui_LabelScreenBrightness;
extern lv_obj_t * ui_ImageScreenBrightness;
//extern lv_obj_t * ui_PanelAlarm;
//extern lv_obj_t * ui_LabelAlarm;
//extern lv_obj_t * ui_ImageAlarmClk;
//void ui_event_SwitchAlarm(lv_event_t * e);
//extern lv_obj_t * ui_SwitchAlarm;
//extern lv_obj_t * ui_PanelTurnOffLcd;
extern lv_obj_t * ui_LabelTurnOffLcd;
extern lv_obj_t * ui_ImageTurnOffLcd;
void ui_event_SwitchTurnOfLcd(lv_event_t * e);
extern lv_obj_t * ui_SwitchTurnOfLcd;
//extern lv_obj_t * ui_PanelTaiWangLiangPing;
void ui_event_SwitchTaiWanLiangPing(lv_event_t * e);
extern lv_obj_t * ui_SwitchTaiWanLiangPing;
extern lv_obj_t * ui_LabelTaiwanLiangPing;
extern lv_obj_t * ui_ImageTaiwanliangping;
//extern lv_obj_t * ui_PanelLongSit;
extern lv_obj_t * ui_LabelLongSit;
extern lv_obj_t * ui_ImageLongSitTX;
void ui_event_SwitchLongSit(lv_event_t * e);
extern lv_obj_t * ui_SwitchLongSit;
// SCREEN: ui_ScreenHRSPO2H
void ui_ScreenHRSPO2H_screen_init(void);
void ui_event_ScreenHRSPO2H(lv_event_t * e);
extern lv_obj_t * ui_ScreenHRSPO2H;
extern lv_obj_t * ui_PanelHR;
extern lv_obj_t * ui_SliderHR;
extern lv_obj_t * ui_LabelHR;
extern lv_obj_t * ui_ImageHR;
extern lv_obj_t * ui_PanelSPO2H;
extern lv_obj_t * ui_SliderSPO2H;
extern lv_obj_t * ui_LabelSPO2H;
extern lv_obj_t * ui_ImageSPO2H;
// SCREEN: ui_ScreenBrightness
void ui_ScreenBrightness_screen_init(void);
void ui_event_ScreenBrightness(lv_event_t * e);
extern lv_obj_t * ui_ScreenBrightness;
void ui_event_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_ImageBrightness;
extern lv_obj_t * ui_LabelBrightness;
// SCREEN: ui_ScreenCalendar
void ui_ScreenCalendar_screen_init(void);
void ui_event_ScreenCalendar(lv_event_t * e);
extern lv_obj_t * ui_ScreenCalendar;
extern lv_obj_t * ui_Calendar;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_bushu_png);    // assets/bushu.png
LV_IMG_DECLARE(ui_img_xieyang_png);    // assets/xieyang.png
LV_IMG_DECLARE(ui_img_xinshuai_png);    // assets/xinshuai.png
LV_IMG_DECLARE(ui_img_lanya_png);    // assets/lanya.png
LV_IMG_DECLARE(ui_img_alarm_clock_png);    // assets/alarm_clock.png
LV_IMG_DECLARE(ui_img_jiuzuotixing_png);    // assets/jiuzuotixing.png
LV_IMG_DECLARE(ui_img_shidu_png);    // assets/shidu.png
LV_IMG_DECLARE(ui_img_wendu_png);    // assets/wendu.png
LV_IMG_DECLARE(ui_img_rili_png);    // assets/rili.png
LV_IMG_DECLARE(ui_img_xinlv_png);    // assets/xinlv.png
LV_IMG_DECLARE(ui_img_pingmuliangdu_hr_png);    // assets/pingmuliangdu_hr.png
LV_IMG_DECLARE(ui_img_naozhong_huaban_png);    // assets/naozhong_huaban.png
LV_IMG_DECLARE(ui_img_xiping_png);    // assets/xiping.png
LV_IMG_DECLARE(ui_img_taiwanliangping_png);    // assets/taiwanliangping.png
LV_IMG_DECLARE(ui_img_jiuzuotixingqiyongqianse_png);    // assets/jiuzuotixingqiyongqianse.png
LV_IMG_DECLARE(ui_img_hr_png);    // assets/HR.png
LV_IMG_DECLARE(ui_img_spo2h_png);    // assets/spo2h.png
LV_IMG_DECLARE(ui_img_jiangdipingmuliangdu_png);    // assets/jiangdipingmuliangdu.png
LV_IMG_DECLARE(ui_img_xiezi_xiao_png); 
LV_IMG_DECLARE(ui_img_394393243); 
LV_IMG_DECLARE(ui_img_1737115695); 
LV_IMG_DECLARE(ui_img_1102958715); 


LV_FONT_DECLARE(ui_font_CuYuan23);
LV_FONT_DECLARE(ui_font_CuYuan60);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
