// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void LoadScreenMenu(lv_event_t * e);
void AlarmSwitch(lv_event_t * e);
void SelfTurnOfflcdSwitch(lv_event_t * e);
void RaiseWristTurnOnLcdSwitch(lv_event_t * e);
void LongSitSwitch(lv_event_t * e);
void LoadScreenHRSPO2H(lv_event_t * e);
void UnLoadScreenSPO2H(lv_event_t * e);
void LoadSceenBrightness(lv_event_t * e);
void LcdBrightnessSlider(lv_event_t * e);
void LoadScreenCalendar(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
