// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "ui.h"
#include "includes.h"

void LoadScreenMenu(lv_event_t * e)
{	
	/* 加载此屏幕设置闹钟开关状态 */
	/*if(g_rtc_alarm_switch)
		lv_obj_add_state(ui_SwitchAlarm,LV_STATE_CHECKED);
	else
		lv_obj_clear_state(ui_SwitchAlarm, LV_STATE_CHECKED);*/
	
	/* 加载此屏幕设置自动熄屏开关状态 */
	if(g_lcd_self_turn_off_switch)
		lv_obj_add_state(ui_SwitchTurnOfLcd,LV_STATE_CHECKED);
	else
		lv_obj_clear_state(ui_SwitchTurnOfLcd, LV_STATE_CHECKED);
	
	/*加载此屏幕设置久坐提醒开关状态 */
	if(g_sedentary_switch)
		lv_obj_add_state(ui_SwitchLongSit,LV_STATE_CHECKED);
	else
		lv_obj_clear_state(ui_SwitchLongSit, LV_STATE_CHECKED);
	
	/* 加载此屏幕设置抬腕亮屏开关状态 */
	if(g_raise_wrist_turn_on_lcd_switch)
		lv_obj_add_state(ui_SwitchTaiWanLiangPing,LV_STATE_CHECKED);
	else
		lv_obj_clear_state(ui_SwitchTaiWanLiangPing, LV_STATE_CHECKED);
}

void AlarmSwitch(lv_event_t * e)
{	
	uint8_t sw = 0;

//	sw = lv_obj_has_state(ui_SwitchAlarm, LV_STATE_CHECKED); 
	
	if(sw)
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_rtc_alarm_switch = 1;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();	

		RTC_AlarmCmd(RTC_Alarm_A,ENABLE);

		dgb_printf_safe("[AlarmSwitch]:alarm on\r\n");
	}
	else
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_rtc_alarm_switch = 0;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();
		
		RTC_AlarmCmd(RTC_Alarm_A,DISABLE);

		dgb_printf_safe("[AlarmSwitch]:alarm off\r\n");
	}
}

void LongSitSwitch(lv_event_t * e)
{
	uint8_t sw = 0;

	sw = lv_obj_has_state(ui_SwitchLongSit, LV_STATE_CHECKED); 

	if(sw)
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_sedentary_switch = 1;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();	

		/* 解除久坐提醒任务的挂起状态 */
		vTaskResume(app_task_sedentary_remind_handle);

		dgb_printf_safe("[LongSitSwitch]:app_task_sedentary_remind resume...\r\n");

		dgb_printf_safe("[LongSitSwitch]:LongSit on\r\n");
	}
	else
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_sedentary_switch = 0;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();

		/* 挂起久坐提醒任务 */
		vTaskSuspend(app_task_sedentary_remind_handle);

		dgb_printf_safe("[LongSitSwitch]:app_task_sedentary_remind supend...\r\n");

		dgb_printf_safe("[LongSitSwitch]:LongSit off\r\n");
	}
}


void RaiseWristTurnOnLcdSwitch(lv_event_t * e)
{
	uint8_t sw = 0;

	sw = lv_obj_has_state(ui_SwitchTaiWanLiangPing, LV_STATE_CHECKED); 

	if(sw)
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_raise_wrist_turn_on_lcd_switch = 1;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();	

		dgb_printf_safe("[RaiseWristTurnOnLcdSwitch]:RaiseWristTurnOnLcdSwitch On\r\n");
	}
	else
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_raise_wrist_turn_on_lcd_switch = 0;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();

		dgb_printf_safe("[RaiseWristTurnOnLcdSwitch]:RaiseWristTurnOnLcdSwitch off\r\n");
	}
}


void SelfTurnOfflcdSwitch(lv_event_t * e)
{
	uint8_t sw = 0;

	sw = lv_obj_has_state(ui_SwitchTurnOfLcd, LV_STATE_CHECKED); 

	if(sw)
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_lcd_self_turn_off_switch = 1;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();	

		dgb_printf_safe("[SelfTurnOfflcdSwitch]:SelfTurnOfflcdSwitch On\r\n");
	}
	else
	{
		/* 进入临界区 */
	    taskENTER_CRITICAL();
		
		g_lcd_self_turn_off_switch = 0;
		
		/* 退出临界区 */
	    taskEXIT_CRITICAL();

		dgb_printf_safe("[SelfTurnOfflcdSwitch]:SelfTurnOfflcdSwitch off\r\n");
	}
}

void LcdBrightnessSlider(lv_event_t * e)
{
	uint32_t slider_value = 0;

	slider_value =  lv_slider_get_value(ui_SliderBrightness);

	/* 设置lcd亮度 */

	/* 进入临界区 */
	taskENTER_CRITICAL();

	g_lcd_brightness = slider_value;
	/* 退出临界区 */
	taskEXIT_CRITICAL();

	lcd_set_brightness(g_lcd_brightness);

	dgb_printf_safe("[LcdBrightnessSlider]:lcd brightness set %d\r\n",g_lcd_brightness);
}

void LoadSceenBrightness(lv_event_t * e)
{
	/* 加载屏幕设置滑块当前屏幕亮度 */
	lv_slider_set_value(ui_SliderBrightness,g_lcd_brightness,LV_ANIM_OFF);
}

void LoadScreenHRSPO2H(lv_event_t * e)
{
	/* 挂起一些任务 */
	vTaskSuspend(app_task_rtc_handle);

	dgb_printf_safe("[LoadScreenHRSPO2H]:app_task_rtc supend\r\n");

	vTaskSuspend(app_task_dht11_handle);

	dgb_printf_safe("[LoadScreenHRSPO2H]:app_task_dht11 supend\r\n");

	vTaskSuspend(app_task_ble_handlde);

	dgb_printf_safe("[LoadScreenHRSPO2H]:app_task_ble supend\r\n");

	vTaskSuspend(app_task_icon_handlde);

	dgb_printf_safe("[LoadScreenHRSPO2H]:app_task_icon supend\r\n");
	
	/* 恢复心率血氧任务 */
	vTaskResume(app_task_max30102_handle);

	dgb_printf_safe("[LoadScreenHRSPO2H]:app_task_max30102 resume\r\n");
}

void UnLoadScreenSPO2H(lv_event_t * e)
{
	/* 恢复一些任务 */
	vTaskResume(app_task_rtc_handle);

	dgb_printf_safe("[UnLoadScreenSPO2H]:app_task_rtc resume\r\n");

	vTaskResume(app_task_dht11_handle);

	dgb_printf_safe("[UnLoadScreenSPO2H]:app_task_dht11 resume\r\n");

	vTaskResume(app_task_ble_handlde);

	dgb_printf_safe("[UnLoadScreenSPO2H]:app_task_ble resume\r\n");

	vTaskResume(app_task_icon_handlde);

	dgb_printf_safe("[UnLoadScreenSPO2H]:app_task_icon resume\r\n");

	/* 挂起心率血氧任务 */
	vTaskSuspend(app_task_max30102_handle);

	dgb_printf_safe("[UnLoadScreenSPO2H]:app_task_max30102 supend\r\n");
}

void LoadScreenCalendar(lv_event_t * e)
{
	RTC_DateTypeDef RTC_DateStruct;

	/* 获取年月日 */
	RTC_GetDate(RTC_Format_BIN,&RTC_DateStruct);

	/* 设置日历部件的年月日 */
	lv_calendar_set_today_date(ui_Calendar,RTC_DateStruct.RTC_Year+2000,RTC_DateStruct.RTC_Month,RTC_DateStruct.RTC_Date);

	/* 设置日历部件当前显示的年月位置 */
	lv_calendar_set_showed_date(ui_Calendar,RTC_DateStruct.RTC_Year+2000,RTC_DateStruct.RTC_Month);
	
	dgb_printf_safe("[LoadScreenCalendar]: Year:%d Month:%d Date:%d\r\n",  RTC_DateStruct.RTC_Year+2000,
																		   RTC_DateStruct.RTC_Month,
																		   RTC_DateStruct.RTC_Date);
}
