// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "../ui.h"

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTime = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelTime, 160);
    lv_obj_set_height(ui_PanelTime, 61);
    lv_obj_set_x(ui_PanelTime, 0);
    lv_obj_set_y(ui_PanelTime, 7);
    lv_obj_set_align(ui_PanelTime, LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHour = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHour, -2);
    lv_obj_set_y(ui_LabelHour, 0);
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelHour, "10");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelHour, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelHour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMin = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelMin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMin, 9);
    lv_obj_set_y(ui_LabelMin, 0);
    lv_obj_set_align(ui_LabelMin, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelMin, "30");
    lv_obj_set_style_text_font(ui_LabelMin, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelfenhao = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_Labelfenhao, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelfenhao, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelfenhao, 0);
    lv_obj_set_y(ui_Labelfenhao, -5);
    lv_obj_set_align(ui_Labelfenhao, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelfenhao, ":");
    lv_obj_set_style_text_color(ui_Labelfenhao, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelfenhao, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Labelfenhao, &ui_font_CuYuan60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 5);
    lv_obj_set_y(ui_LabelDate, 63);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_LabelDate, "2024/10/12");
    lv_obj_set_style_text_color(ui_LabelDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeek = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeek, 120);
    lv_obj_set_y(ui_LabelWeek, 63);
    lv_obj_set_align(ui_LabelWeek, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_LabelWeek, "Thu");
    lv_obj_set_style_text_color(ui_LabelWeek, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeek, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHealth = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelHealth, 240);
    lv_obj_set_height(ui_PanelHealth, 120);
    lv_obj_set_x(ui_PanelHealth, -5);
    lv_obj_set_y(ui_PanelHealth, 102);
    lv_obj_set_align(ui_PanelHealth, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHealth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHealth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHealth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHealth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHealth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcStepNum = lv_arc_create(ui_PanelHealth);
    lv_obj_set_width(ui_ArcStepNum, 140);
    lv_obj_set_height(ui_ArcStepNum, 140);
    lv_obj_set_x(ui_ArcStepNum, 35);
    lv_obj_set_y(ui_ArcStepNum, 10);
    lv_obj_set_align(ui_ArcStepNum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcStepNum, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcStepNum, 0, 5000);
    lv_arc_set_value(ui_ArcStepNum, 0);
    lv_arc_set_bg_angles(ui_ArcStepNum, 180, 360);
    lv_obj_set_style_arc_color(ui_ArcStepNum, lv_color_hex(0xECBF05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcStepNum, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcStepNum, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcStepNum, lv_color_hex(0xECBF05), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcStepNum, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcStepNum, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcStepNum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcStepNum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcHeartRate = lv_arc_create(ui_PanelHealth);
    lv_obj_set_width(ui_ArcHeartRate, 110);
    lv_obj_set_height(ui_ArcHeartRate, 110);
    lv_obj_set_x(ui_ArcHeartRate, 35);
    lv_obj_set_y(ui_ArcHeartRate, 10);
    lv_obj_set_align(ui_ArcHeartRate, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcHeartRate, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_ArcHeartRate, 0, 120);
    lv_arc_set_value(ui_ArcHeartRate, 0);
    lv_arc_set_bg_angles(ui_ArcHeartRate, 180, 360);
    lv_obj_set_style_arc_color(ui_ArcHeartRate, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHeartRate, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcHeartRate, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHeartRate, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHeartRate, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcHeartRate, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHeartRate, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHeartRate, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcBloodOxygen = lv_arc_create(ui_PanelHealth);
    lv_obj_set_width(ui_ArcBloodOxygen, 80);
    lv_obj_set_height(ui_ArcBloodOxygen, 80);
    lv_obj_set_x(ui_ArcBloodOxygen, 35);
    lv_obj_set_y(ui_ArcBloodOxygen, 10);
    lv_obj_set_align(ui_ArcBloodOxygen, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcBloodOxygen, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcBloodOxygen, 0);
    lv_arc_set_bg_angles(ui_ArcBloodOxygen, 180, 360);
    lv_obj_set_style_arc_color(ui_ArcBloodOxygen, lv_color_hex(0x28BE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBloodOxygen, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcBloodOxygen, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcBloodOxygen, lv_color_hex(0x28BE72), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcBloodOxygen, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcBloodOxygen, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcBloodOxygen, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcBloodOxygen, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelKeepOn = lv_label_create(ui_PanelHealth);
    lv_obj_set_width(ui_LabelKeepOn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKeepOn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelKeepOn, 38);
    lv_obj_set_y(ui_LabelKeepOn, 25);
    lv_obj_set_align(ui_LabelKeepOn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelKeepOn, "Keep Skate");
    lv_obj_set_style_text_color(ui_LabelKeepOn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelKeepOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelKeepOn, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStepNum = lv_label_create(ui_PanelHealth);
    lv_obj_set_width(ui_LabelStepNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStepNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStepNum, 30);
    lv_obj_set_y(ui_LabelStepNum, -15);
    lv_label_set_text(ui_LabelStepNum, "00");
    lv_obj_set_style_text_color(ui_LabelStepNum, lv_color_hex(0xECBF05), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStepNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStepNum, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageStepNum = lv_img_create(ui_PanelHealth);
    lv_img_set_src(ui_ImageStepNum, &ui_img_bushu_png);
    lv_obj_set_width(ui_ImageStepNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageStepNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageStepNum, 2);
    lv_obj_set_y(ui_ImageStepNum, -15);
    lv_obj_add_flag(ui_ImageStepNum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageStepNum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBloodOxygen = lv_label_create(ui_PanelHealth);
    lv_obj_set_width(ui_LabelBloodOxygen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBloodOxygen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBloodOxygen, 30);
    lv_obj_set_y(ui_LabelBloodOxygen, 15);
    lv_obj_set_align(ui_LabelBloodOxygen, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelBloodOxygen, "00");
    lv_obj_set_style_text_color(ui_LabelBloodOxygen, lv_color_hex(0x28BE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBloodOxygen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBloodOxygen, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBloodOxygen = lv_img_create(ui_PanelHealth);
    lv_img_set_src(ui_ImageBloodOxygen, &ui_img_xieyang_png);
    lv_obj_set_width(ui_ImageBloodOxygen, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBloodOxygen, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageBloodOxygen, 4);
    lv_obj_set_y(ui_ImageBloodOxygen, 15);
    lv_obj_set_align(ui_ImageBloodOxygen, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageBloodOxygen, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBloodOxygen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHeartRate = lv_label_create(ui_PanelHealth);
    lv_obj_set_width(ui_LabelHeartRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHeartRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHeartRate, 30);
    lv_obj_set_y(ui_LabelHeartRate, -15);
    lv_obj_set_align(ui_LabelHeartRate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelHeartRate, "00");
    lv_obj_set_style_text_color(ui_LabelHeartRate, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHeartRate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHeartRate, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHeartRate = lv_img_create(ui_PanelHealth);
    lv_img_set_src(ui_ImageHeartRate, &ui_img_xinshuai_png);
    lv_obj_set_width(ui_ImageHeartRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHeartRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHeartRate, 0);
    lv_obj_set_y(ui_ImageHeartRate, -15);
    lv_obj_set_align(ui_ImageHeartRate, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageHeartRate, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHeartRate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Imageble = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Imageble, &ui_img_lanya_png);
    lv_obj_set_width(ui_Imageble, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Imageble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Imageble, -15);
    lv_obj_set_y(ui_Imageble, 10);
    lv_obj_set_align(ui_Imageble, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Imageble, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imageble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageAlarm = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_ImageAlarm, &ui_img_alarm_clock_png);
    lv_obj_set_width(ui_ImageAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageAlarm, -50);
    lv_obj_set_y(ui_ImageAlarm, 10);
    lv_obj_set_align(ui_ImageAlarm, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageAlarm, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageAlarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLongSit = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_ImageLongSit, &ui_img_jiuzuotixing_png);
    lv_obj_set_width(ui_ImageLongSit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLongSit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLongSit, -85);
    lv_obj_set_y(ui_ImageLongSit, 10);
    lv_obj_set_align(ui_ImageLongSit, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageLongSit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLongSit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelHum = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelHum, 70);
    lv_obj_set_height(ui_PanelHum, 65);
    lv_obj_set_x(ui_PanelHum, -5);
    lv_obj_set_y(ui_PanelHum, 10);
    lv_obj_set_align(ui_PanelHum, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcHum = lv_arc_create(ui_PanelHum);
    lv_obj_set_width(ui_ArcHum, 65);
    lv_obj_set_height(ui_ArcHum, 65);
    lv_obj_set_align(ui_ArcHum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcHum, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcHum, 0);
    lv_arc_set_bg_angles(ui_ArcHum, 0, 270);
    lv_arc_set_rotation(ui_ArcHum, 315);
    lv_obj_set_style_arc_color(ui_ArcHum, lv_color_hex(0x10C6DC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHum, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHum, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHum, lv_color_hex(0x10C6DC), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHum, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHum, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHum, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHum, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageHum = lv_img_create(ui_PanelHum);
    lv_img_set_src(ui_ImageHum, &ui_img_shidu_png);
    lv_obj_set_width(ui_ImageHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHum, 0);
    lv_obj_set_y(ui_ImageHum, -22);
    lv_obj_set_align(ui_ImageHum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHum, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelHum = lv_label_create(ui_PanelHum);
    lv_obj_set_width(ui_LabelHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHum, "00");

    ui_PanelTem = lv_obj_create(ui_ScreenHome);
    lv_obj_set_width(ui_PanelTem, 70);
    lv_obj_set_height(ui_PanelTem, 65);
    lv_obj_set_x(ui_PanelTem, -5);
    lv_obj_set_y(ui_PanelTem, -60);
    lv_obj_set_align(ui_PanelTem, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelTem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTem, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTem = lv_arc_create(ui_PanelTem);
    lv_obj_set_width(ui_ArcTem, 65);
    lv_obj_set_height(ui_ArcTem, 65);
    lv_obj_set_align(ui_ArcTem, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArcTem, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_ArcTem, 0);
    lv_arc_set_bg_angles(ui_ArcTem, 0, 270);
    lv_arc_set_rotation(ui_ArcTem, 315);
    lv_obj_set_style_arc_color(ui_ArcTem, lv_color_hex(0xFC0808), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTem, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTem, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTem, lv_color_hex(0xFC0808), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTem, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTem, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTem, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTem, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageTem = lv_img_create(ui_ArcTem);
    lv_img_set_src(ui_ImageTem, &ui_img_wendu_png);
    lv_obj_set_width(ui_ImageTem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTem, 0);
    lv_obj_set_y(ui_ImageTem, -22);
    lv_obj_set_align(ui_ImageTem, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTem, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTem = lv_label_create(ui_ArcTem);
    lv_obj_set_width(ui_LabelTem, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTem, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTem, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTem, "00.0");

    lv_obj_add_event_cb(ui_ScreenHome, ui_event_ScreenHome, LV_EVENT_ALL, NULL);
	
	
	ui_Image2 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image2, &ui_img_394393243);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -90);
    lv_obj_set_y(ui_Image2, -29);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
	
	ui_Image3 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image3, &ui_img_xiezi_xiao_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -42);
    lv_obj_set_y(ui_Image3, -29);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
	
	ui_Image1 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image1, &ui_img_1737115695);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 11);
    lv_obj_set_y(ui_Image1, -29);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
	
	ui_Image4 = lv_img_create(ui_ScreenHome);
    lv_img_set_src(ui_Image4, &ui_img_1102958715);
    lv_obj_set_width(ui_Image4, 161);
    lv_obj_set_height(ui_Image4, 25);
    lv_obj_set_x(ui_Image4, -46);
    lv_obj_set_y(ui_Image4, 12);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
	

}
