// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "../ui.h"

void ui_ScreenMenu_screen_init(void)
{
    ui_ScreenMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMenu = lv_obj_create(ui_ScreenMenu);
    lv_obj_set_width(ui_PanelMenu, 240);
    lv_obj_set_height(ui_PanelMenu, 280);
    lv_obj_set_align(ui_PanelMenu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelMenu, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_set_scroll_dir(ui_PanelMenu, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_PanelMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCalendar = lv_obj_create(ui_PanelMenu);
    lv_obj_set_width(ui_PanelCalendar, 240);
    lv_obj_set_height(ui_PanelCalendar, 50);
    lv_obj_set_x(ui_PanelCalendar, 0);
    lv_obj_set_y(ui_PanelCalendar, -115);
    lv_obj_set_align(ui_PanelCalendar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelCalendar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCalendar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCalendar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCalendar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCalendar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PanelCalendar, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PanelCalendar, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelCalendar, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelCalendar = lv_label_create(ui_PanelCalendar);
    lv_obj_set_width(ui_LabelCalendar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCalendar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCalendar, 1);
    lv_obj_set_y(ui_LabelCalendar, 0);
    lv_obj_set_align(ui_LabelCalendar, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCalendar, "Calendar");
    lv_obj_set_style_text_color(ui_LabelCalendar, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCalendar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCalendar, &ui_font_CuYuan23, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHRSPO3 = lv_img_create(ui_PanelCalendar);
    lv_img_set_src(ui_ImageHRSPO3, &ui_img_rili_png);
    lv_obj_set_width(ui_ImageHRSPO3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHRSPO3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHRSPO3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageHRSPO3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHRSPO3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelHRSPO2H = lv_obj_create(ui_PanelMenu);
    lv_obj_set_width(ui_PanelHRSPO2H, 240);
    lv_obj_set_height(ui_PanelHRSPO2H, 50);
    lv_obj_set_x(ui_PanelHRSPO2H, 0);
    lv_obj_set_y(ui_PanelHRSPO2H, -55);
    lv_obj_set_align(ui_PanelHRSPO2H, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelHRSPO2H, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHRSPO2H, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHRSPO2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHRSPO2H, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHRSPO2H, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PanelHRSPO2H, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PanelHRSPO2H, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelHRSPO2H, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelHRSPO2H = lv_label_create(ui_PanelHRSPO2H);
    lv_obj_set_width(ui_LabelHRSPO2H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHRSPO2H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHRSPO2H, 15);
    lv_obj_set_y(ui_LabelHRSPO2H, 0);
    lv_obj_set_align(ui_LabelHRSPO2H, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHRSPO2H, "Heart rate ");
    lv_obj_set_style_text_color(ui_LabelHRSPO2H, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHRSPO2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHRSPO2H, &ui_font_CuYuan23, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHRSPO2 = lv_img_create(ui_PanelHRSPO2H);
    lv_img_set_src(ui_ImageHRSPO2, &ui_img_xinlv_png);
    lv_obj_set_width(ui_ImageHRSPO2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHRSPO2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHRSPO2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageHRSPO2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHRSPO2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelScreenBrightness = lv_obj_create(ui_PanelMenu);
    lv_obj_set_width(ui_PanelScreenBrightness, 240);
    lv_obj_set_height(ui_PanelScreenBrightness, 50);
    lv_obj_set_x(ui_PanelScreenBrightness, 0);
    lv_obj_set_y(ui_PanelScreenBrightness, 5);
    lv_obj_set_align(ui_PanelScreenBrightness, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelScreenBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScreenBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScreenBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelScreenBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelScreenBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_PanelScreenBrightness, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_PanelScreenBrightness, lv_color_hex(0xA1A1A1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_PanelScreenBrightness, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelScreenBrightness = lv_label_create(ui_PanelScreenBrightness);
    lv_obj_set_width(ui_LabelScreenBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenBrightness, 15);
    lv_obj_set_y(ui_LabelScreenBrightness, 0);
    lv_obj_set_align(ui_LabelScreenBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenBrightness, "Brightness");
    lv_obj_set_style_text_color(ui_LabelScreenBrightness, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelScreenBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelScreenBrightness, &ui_font_CuYuan23, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageScreenBrightness = lv_img_create(ui_PanelScreenBrightness);
    lv_img_set_src(ui_ImageScreenBrightness, &ui_img_pingmuliangdu_hr_png);
    lv_obj_set_width(ui_ImageScreenBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageScreenBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageScreenBrightness, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageScreenBrightness, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageScreenBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PanelCalendar, ui_event_PanelCalendar, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelHRSPO2H, ui_event_PanelHRSPO2H, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PanelScreenBrightness, ui_event_PanelScreenBrightness, LV_EVENT_ALL, NULL);
//    lv_obj_add_event_cb(ui_SwitchAlarm, ui_event_SwitchAlarm, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenMenu, ui_event_ScreenMenu, LV_EVENT_ALL, NULL);

}
