// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "../ui.h"

void ui_ScreenHRSPO2H_screen_init(void)
{
    ui_ScreenHRSPO2H = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenHRSPO2H, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenHRSPO2H, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenHRSPO2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHR = lv_obj_create(ui_ScreenHRSPO2H);
    lv_obj_set_width(ui_PanelHR, 100);
    lv_obj_set_height(ui_PanelHR, 280);
    lv_obj_set_x(ui_PanelHR, 20);
    lv_obj_set_y(ui_PanelHR, 0);
    lv_obj_clear_flag(ui_PanelHR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelHR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderHR = lv_slider_create(ui_PanelHR);
    lv_slider_set_range(ui_SliderHR, 0, 120);
    lv_slider_set_value(ui_SliderHR, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderHR) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderHR, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderHR, 20);
    lv_obj_set_height(ui_SliderHR, 160);
    lv_obj_set_align(ui_SliderHR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderHR, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SliderHR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderHR, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderHR, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderHR, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderHR, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderHR, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelHR = lv_label_create(ui_PanelHR);
    lv_obj_set_width(ui_LabelHR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelHR, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelHR, "0");
    lv_obj_set_style_text_color(ui_LabelHR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHR, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHR = lv_img_create(ui_PanelHR);
    lv_img_set_src(ui_ImageHR, &ui_img_hr_png);
    lv_obj_set_width(ui_ImageHR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHR, 0);
    lv_obj_set_y(ui_ImageHR, -10);
    lv_obj_set_align(ui_ImageHR, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImageHR, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHR, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelSPO2H = lv_obj_create(ui_ScreenHRSPO2H);
    lv_obj_set_width(ui_PanelSPO2H, 100);
    lv_obj_set_height(ui_PanelSPO2H, 280);
    lv_obj_set_x(ui_PanelSPO2H, -20);
    lv_obj_set_y(ui_PanelSPO2H, 0);
    lv_obj_set_align(ui_PanelSPO2H, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PanelSPO2H, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSPO2H, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSPO2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSPO2H, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSPO2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderSPO2H = lv_slider_create(ui_PanelSPO2H);
    lv_slider_set_range(ui_SliderSPO2H, 0, 101);
    lv_slider_set_value(ui_SliderSPO2H, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderSPO2H) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderSPO2H, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderSPO2H, 20);
    lv_obj_set_height(ui_SliderSPO2H, 160);
    lv_obj_set_align(ui_SliderSPO2H, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderSPO2H, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SliderSPO2H, lv_color_hex(0x28BE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSPO2H, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSPO2H, lv_color_hex(0x28BE72), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSPO2H, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderSPO2H, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderSPO2H, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelSPO2H = lv_label_create(ui_PanelSPO2H);
    lv_obj_set_width(ui_LabelSPO2H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSPO2H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSPO2H, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelSPO2H, "0");
    lv_obj_set_style_text_color(ui_LabelSPO2H, lv_color_hex(0x28BE72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSPO2H, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSPO2H, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageSPO2H = lv_img_create(ui_PanelSPO2H);
    lv_img_set_src(ui_ImageSPO2H, &ui_img_spo2h_png);
    lv_obj_set_width(ui_ImageSPO2H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageSPO2H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageSPO2H, 5);
    lv_obj_set_y(ui_ImageSPO2H, -10);
    lv_obj_set_align(ui_ImageSPO2H, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_ImageSPO2H, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSPO2H, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ScreenHRSPO2H, ui_event_ScreenHRSPO2H, LV_EVENT_ALL, NULL);

}
