// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SmartWatch

#include "../ui.h"

void ui_ScreenBrightness_screen_init(void)
{
    ui_ScreenBrightness = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SliderBrightness = lv_slider_create(ui_ScreenBrightness);
    lv_slider_set_value(ui_SliderBrightness, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightness, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 230);
    lv_obj_set_height(ui_SliderBrightness, 50);
    lv_obj_set_x(ui_SliderBrightness, 0);
    lv_obj_set_y(ui_SliderBrightness, 50);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SliderBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderBrightness, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ImageBrightness = lv_img_create(ui_SliderBrightness);
    lv_img_set_src(ui_ImageBrightness, &ui_img_jiangdipingmuliangdu_png);
    lv_obj_set_width(ui_ImageBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_add_flag(ui_ImageBrightness, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBrightness = lv_label_create(ui_ScreenBrightness);
    lv_obj_set_width(ui_LabelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightness, 0);
    lv_obj_set_y(ui_LabelBrightness, -30);
    lv_obj_set_align(ui_LabelBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBrightness, "Brightness");
    lv_obj_set_style_text_font(ui_LabelBrightness, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenBrightness, ui_event_ScreenBrightness, LV_EVENT_ALL, NULL);

}
